function ingredient(id, name, category, aliases, common) {
  return {
    id,
    name,
    category,
    common: Boolean(common),
    image: `/assets/images/ingredients/extra/${id}.jpg`,
    aliases: aliases || []
  };
}

function recipe(config) {
  return {
    rating: config.rating || 4.6,
    fatLoss: Boolean(config.fatLoss),
    image: `/assets/images/recipes/extra/${config.id}.jpg`,
    ...config,
    ingredients: config.ingredients.map(([name, amount]) => ({ name, amount }))
  };
}

const ingredientCategories = [
  { id: 'common', name: '常用' },
  { id: 'vegetable', name: '蔬菜' },
  { id: 'meat', name: '肉类' },
  { id: 'egg', name: '蛋类' },
  { id: 'soy', name: '豆制品' },
  { id: 'seafood', name: '海鲜水产' },
  { id: 'staple', name: '主食' },
  { id: 'fruit', name: '水果' },
  { id: 'seasoning', name: '调味' }
];

const categoryOverrides = {
  egg: 'egg',
  shrimp: 'seafood',
  beef: 'meat',
  pork: 'meat',
  chicken_thigh: 'meat',
  chicken_breast: 'meat',
  chicken_wing: 'meat',
  pork_belly: 'meat',
  ham_sausage: 'meat',
  fish_fillet: 'seafood',
  tofu: 'soy'
};

const extraIngredients = [
  ingredient('cabbage', '白菜', 'vegetable', ['大白菜'], true),
  ingredient('rapeseed_greens', '油菜', 'vegetable', ['上海青'], false),
  ingredient('youmai', '油麦菜', 'vegetable', [], false),
  ingredient('celery', '芹菜', 'vegetable', [], false),
  ingredient('chive', '韭菜', 'vegetable', [], false),
  ingredient('yam', '山药', 'vegetable', [], false),
  ingredient('lotus_root', '莲藕', 'vegetable', ['藕'], false),
  ingredient('long_bean', '豆角', 'vegetable', ['豇豆'], false),
  ingredient('cauliflower', '菜花', 'vegetable', ['花菜'], false),
  ingredient('black_fungus', '木耳', 'vegetable', ['黑木耳'], false),
  ingredient('cilantro', '香菜', 'seasoning', ['芫荽'], false),
  ingredient('pork_loin', '里脊肉', 'meat', ['猪里脊'], false),
  ingredient('ribs', '排骨', 'meat', ['猪排骨'], false),
  ingredient('pig_trotter', '猪蹄', 'meat', [], false),
  ingredient('lamb', '羊肉', 'meat', [], false),
  ingredient('duck_leg', '鸭腿', 'meat', [], false),
  ingredient('ham', '火腿', 'meat', [], false),
  ingredient('duck_egg', '鸭蛋', 'egg', [], false),
  ingredient('quail_egg', '鹌鹑蛋', 'egg', [], false),
  ingredient('century_egg', '皮蛋', 'egg', ['松花蛋'], false),
  ingredient('salted_duck_egg', '咸鸭蛋', 'egg', ['咸蛋'], false),
  ingredient('soft_tofu', '嫩豆腐', 'soy', ['内酯豆腐'], false),
  ingredient('firm_tofu', '老豆腐', 'soy', ['北豆腐'], false),
  ingredient('tofu_skin', '千张', 'soy', ['豆皮'], false),
  ingredient('tofu_dry', '豆腐干', 'soy', ['豆干'], false),
  ingredient('yuba', '腐竹', 'soy', [], false),
  ingredient('fried_tofu', '油豆腐', 'soy', [], false),
  ingredient('soybean_sprouts', '黄豆芽', 'soy', [], false),
  ingredient('mungbean_sprouts', '绿豆芽', 'soy', [], false),
  ingredient('whole_fish', '鱼', 'seafood', ['整鱼', '鲜鱼'], false),
  ingredient('prawn', '基围虾', 'seafood', ['鲜虾'], false),
  ingredient('crayfish', '小龙虾', 'seafood', ['龙虾尾'], false),
  ingredient('crab', '大闸蟹', 'seafood', ['螃蟹'], false),
  ingredient('clam', '花甲', 'seafood', ['蛤蜊'], false),
  ingredient('scallop', '扇贝', 'seafood', [], false),
  ingredient('oyster', '生蚝', 'seafood', ['牡蛎'], false),
  ingredient('squid', '鱿鱼', 'seafood', [], false),
  ingredient('kelp', '海带', 'seafood', [], false),
  ingredient('seaweed', '紫菜', 'seafood', [], false),
  ingredient('flour', '面粉', 'staple', [], false),
  ingredient('mantou', '馒头', 'staple', [], false),
  ingredient('baozi', '包子', 'staple', [], false),
  ingredient('dumpling', '饺子', 'staple', [], false),
  ingredient('rice_noodle', '米粉', 'staple', [], false),
  ingredient('rice_cake', '年糕', 'staple', [], false),
  ingredient('apple', '苹果', 'fruit', [], false),
  ingredient('pear', '梨', 'fruit', ['雪梨'], false),
  ingredient('banana', '香蕉', 'fruit', [], false),
  ingredient('orange', '橙子', 'fruit', [], false),
  ingredient('mandarin', '橘子', 'fruit', ['桔子'], false),
  ingredient('grapefruit', '柚子', 'fruit', [], false),
  ingredient('strawberry', '草莓', 'fruit', [], false),
  ingredient('grape', '葡萄', 'fruit', [], false),
  ingredient('watermelon', '西瓜', 'fruit', [], false),
  ingredient('mango', '芒果', 'fruit', [], false),
  ingredient('dragon_fruit', '火龙果', 'fruit', [], false),
  ingredient('kiwi', '猕猴桃', 'fruit', ['奇异果'], false),
  ingredient('peach', '桃子', 'fruit', [], false),
  ingredient('cherry', '樱桃', 'fruit', [], false)
];

const extraRecipes = [
  recipe({ id: 'stir-cabbage', name: '清炒白菜', subtitle: '便宜清甜，十分钟补一盘蔬菜', category: '素菜', time: 10, difficulty: 1, calories: 120, protein: 4, fatLoss: true, tags: ['清爽', '快手素菜'], mainIngredientIds: ['cabbage'], ingredientIds: ['cabbage', 'garlic'], ingredients: [['白菜', '半颗'], ['大蒜', '2 瓣'], ['盐', '少量'], ['食用油', '少量']], steps: ['白菜洗净切段，大蒜切片。', '锅中少油，放蒜片炒香。', '先放白菜帮翻炒 1 分钟。', '再放白菜叶，加盐快速翻炒。', '白菜刚变软就出锅。'] }),
  recipe({ id: 'mushroom-rapeseed-greens', name: '香菇油菜', subtitle: '清爽鲜香，适合晚餐配饭', category: '素菜', time: 12, difficulty: 1, calories: 150, protein: 6, fatLoss: true, tags: ['清爽', '低油'], mainIngredientIds: ['rapeseed_greens', 'mushroom'], ingredientIds: ['rapeseed_greens', 'mushroom', 'garlic'], ingredients: [['油菜', '1 把'], ['香菇', '5 朵'], ['大蒜', '2 瓣'], ['盐', '适量'], ['生抽', '1 小勺']], steps: ['油菜洗净，香菇切片。', '锅中少油炒香蒜末。', '放香菇炒到变软。', '放油菜大火翻炒。', '加盐和生抽调味出锅。'] }),
  recipe({ id: 'oyster-youmai', name: '蚝油油麦菜', subtitle: '爽脆不寡淡，新手也稳', category: '素菜', time: 8, difficulty: 1, calories: 110, protein: 3, fatLoss: true, tags: ['低卡', '快手'], mainIngredientIds: ['youmai', 'oyster_sauce'], ingredientIds: ['youmai', 'oyster_sauce', 'garlic'], ingredients: [['油麦菜', '1 把'], ['蚝油', '1 小勺'], ['大蒜', '2 瓣'], ['盐', '少量']], steps: ['油麦菜洗净切段。', '锅中少油炒香蒜末。', '放油麦菜大火翻炒。', '加入蚝油和少量盐。', '翻匀后马上出锅。'] }),
  recipe({ id: 'celery-pork-loin', name: '芹菜炒里脊', subtitle: '清香下饭，肉片嫩一点更好吃', category: '家常肉菜', time: 18, difficulty: 2, calories: 320, protein: 30, tags: ['下饭', '快手肉菜'], mainIngredientIds: ['celery', 'pork_loin'], ingredientIds: ['celery', 'pork_loin', 'ginger'], ingredients: [['里脊肉', '180 克'], ['芹菜', '1 把'], ['姜丝', '少量'], ['生抽', '1 汤匙'], ['淀粉', '1 小勺'], ['盐', '少量']], steps: ['里脊切片，加生抽和淀粉抓匀。', '芹菜切段，姜切丝。', '热锅少油，先炒肉片到变色。', '放芹菜和姜丝快速翻炒。', '加盐调味，芹菜断生后出锅。'] }),
  recipe({ id: 'chive-egg', name: '韭菜炒鸡蛋', subtitle: '香气足，十分钟一盘家常菜', category: '家常快手', time: 10, difficulty: 1, calories: 260, protein: 18, tags: ['快手', '家常'], mainIngredientIds: ['chive', 'egg'], ingredientIds: ['chive', 'egg'], ingredients: [['韭菜', '1 把'], ['鸡蛋', '2 个'], ['盐', '少量'], ['食用油', '适量']], steps: ['韭菜洗净切段，鸡蛋打散。', '锅中倒油，先炒鸡蛋成大块。', '盛出鸡蛋备用。', '锅中放韭菜快速翻炒。', '倒回鸡蛋，加盐炒匀出锅。'] }),
  recipe({ id: 'yam-ribs-soup', name: '山药排骨汤', subtitle: '清润暖胃，周末也适合多煮点', category: '汤菜', time: 45, difficulty: 2, calories: 430, protein: 32, tags: ['热汤', '炖菜'], mainIngredientIds: ['yam', 'ribs'], ingredientIds: ['yam', 'ribs', 'ginger', 'scallion'], ingredients: [['排骨', '300 克'], ['山药', '1 段'], ['姜片', '3 片'], ['小葱', '少量'], ['盐', '适量']], steps: ['排骨冷水下锅焯水，冲净浮沫。', '山药去皮切段。', '锅中加排骨、姜片和热水。', '小火煮 30 分钟后放山药。', '山药变软后加盐和小葱。'] }),
  recipe({ id: 'lotus-ribs-soup', name: '莲藕排骨汤', subtitle: '藕香浓一点，晚餐很安心', category: '汤菜', time: 50, difficulty: 2, calories: 460, protein: 32, tags: ['热汤', '炖菜'], mainIngredientIds: ['lotus_root', 'ribs'], ingredientIds: ['lotus_root', 'ribs', 'ginger'], ingredients: [['莲藕', '1 节'], ['排骨', '300 克'], ['姜片', '3 片'], ['盐', '适量']], steps: ['排骨焯水后冲净。', '莲藕去皮切块。', '锅中加排骨、莲藕、姜片和热水。', '小火炖 40 分钟。', '加盐调味即可。'] }),
  recipe({ id: 'dry-long-bean', name: '干煸豆角', subtitle: '香辣下饭，豆角一定要炒熟', category: '家常素菜', time: 22, difficulty: 2, calories: 260, protein: 8, tags: ['下饭', '椒香锅气'], mainIngredientIds: ['long_bean'], ingredientIds: ['long_bean', 'dried_chili', 'garlic'], ingredients: [['豆角', '300 克'], ['干辣椒', '2 个'], ['大蒜', '2 瓣'], ['生抽', '1 小勺'], ['盐', '适量']], steps: ['豆角洗净切段并沥干。', '锅中少油，把豆角煸到表皮起皱。', '放蒜片和干辣椒炒香。', '加生抽和盐翻炒。', '确认豆角熟透后出锅。'] }),
  recipe({ id: 'cauliflower-pork', name: '菜花炒肉片', subtitle: '脆嫩有肉香，带饭也合适', category: '家常肉菜', time: 20, difficulty: 2, calories: 330, protein: 26, tags: ['下饭', '家常'], mainIngredientIds: ['cauliflower', 'pork_loin'], ingredientIds: ['cauliflower', 'pork_loin', 'garlic'], ingredients: [['菜花', '半颗'], ['里脊肉', '150 克'], ['大蒜', '2 瓣'], ['生抽', '1 汤匙'], ['盐', '少量']], steps: ['菜花掰小朵，肉切片。', '菜花焯水 1 分钟。', '锅中少油炒肉片到变色。', '放蒜片和菜花翻炒。', '加生抽和盐调味。'] }),
  recipe({ id: 'fungus-egg', name: '木耳炒鸡蛋', subtitle: '口感脆嫩，厨房新手也好做', category: '家常快手', time: 15, difficulty: 1, calories: 240, protein: 17, fatLoss: true, tags: ['快手', '清爽'], mainIngredientIds: ['black_fungus', 'egg'], ingredientIds: ['black_fungus', 'egg', 'scallion'], ingredients: [['木耳', '1 小把'], ['鸡蛋', '2 个'], ['小葱', '少量'], ['盐', '少量']], steps: ['木耳泡发洗净，鸡蛋打散。', '锅中倒油炒鸡蛋，盛出。', '放木耳翻炒 1 分钟。', '倒回鸡蛋，加盐调味。', '撒小葱出锅。'] }),
  recipe({ id: 'cilantro-beef', name: '香菜拌牛肉', subtitle: '不想开大火时也能吃到肉', category: '凉拌菜', time: 16, difficulty: 2, calories: 300, protein: 32, fatLoss: true, tags: ['清爽', '高蛋白'], mainIngredientIds: ['cilantro', 'beef'], ingredientIds: ['cilantro', 'beef', 'garlic'], ingredients: [['牛肉片', '180 克'], ['香菜', '1 把'], ['大蒜', '1 瓣'], ['生抽', '1 汤匙'], ['香醋', '1 小勺']], steps: ['牛肉片焯熟后沥干。', '香菜切段，大蒜切末。', '生抽、香醋和蒜末调汁。', '牛肉和香菜放入碗中。', '淋汁拌匀即可。'] }),
  recipe({ id: 'sweet-sour-loin', name: '糖醋里脊', subtitle: '酸甜开胃，想吃硬菜时很稳', category: '家常肉菜', time: 28, difficulty: 3, calories: 520, protein: 32, tags: ['酸甜开胃', '下饭'], mainIngredientIds: ['pork_loin'], ingredientIds: ['pork_loin'], ingredients: [['里脊肉', '250 克'], ['淀粉', '2 汤匙'], ['番茄酱', '2 汤匙'], ['糖', '1 汤匙'], ['米醋', '1 汤匙']], steps: ['里脊切条，加盐和淀粉抓匀。', '锅中油热后把肉条煎到金黄。', '番茄酱、糖、醋和水调成汁。', '锅中倒入酱汁煮到起泡。', '放入里脊条裹匀出锅。'] }),
  recipe({ id: 'braised-ribs', name: '红烧排骨', subtitle: '浓郁下饭，一锅主菜就够了', category: '炖菜', time: 45, difficulty: 2, calories: 560, protein: 35, tags: ['红烧', '下饭'], mainIngredientIds: ['ribs'], ingredientIds: ['ribs', 'ginger', 'scallion'], ingredients: [['排骨', '350 克'], ['姜片', '3 片'], ['生抽', '1 汤匙'], ['老抽', '半小勺'], ['冰糖', '少量']], steps: ['排骨焯水后冲净。', '锅中少油炒香姜片和排骨。', '加生抽、老抽和冰糖翻匀。', '加热水没过排骨，小火炖 35 分钟。', '大火收汁即可。'] }),
  recipe({ id: 'braised-trotter', name: '红烧猪蹄', subtitle: '软糯入味，适合提前多炖一点', category: '炖菜', time: 70, difficulty: 3, calories: 680, protein: 42, tags: ['红烧', '硬菜'], mainIngredientIds: ['pig_trotter'], ingredientIds: ['pig_trotter', 'ginger', 'scallion'], ingredients: [['猪蹄', '半只'], ['姜片', '3 片'], ['生抽', '1 汤匙'], ['老抽', '半小勺'], ['盐', '适量']], steps: ['猪蹄焯水后洗净。', '锅中少油炒香姜片。', '放猪蹄和调料翻炒上色。', '加热水小火炖 60 分钟。', '猪蹄软糯后收汁出锅。'] }),
  recipe({ id: 'cumin-lamb', name: '孜然羊肉', subtitle: '香味足，配米饭很痛快', category: '家常肉菜', time: 18, difficulty: 2, calories: 460, protein: 34, tags: ['椒香锅气', '下饭'], mainIngredientIds: ['lamb', 'onion'], ingredientIds: ['lamb', 'onion', 'dried_chili'], ingredients: [['羊肉片', '200 克'], ['洋葱', '半个'], ['孜然粉', '1 小勺'], ['干辣椒', '少量'], ['盐', '少量']], steps: ['羊肉片解冻沥干，洋葱切丝。', '锅热少油，先炒羊肉到变色。', '放洋葱丝和干辣椒翻炒。', '撒孜然粉和盐。', '炒到羊肉熟透出锅。'] }),
  recipe({ id: 'soy-duck-leg', name: '酱香鸭腿', subtitle: '不用太复杂，也能做出卤香味', category: '家常肉菜', time: 45, difficulty: 2, calories: 520, protein: 38, tags: ['酱香', '下饭'], mainIngredientIds: ['duck_leg'], ingredientIds: ['duck_leg', 'ginger', 'scallion'], ingredients: [['鸭腿', '1 只'], ['姜片', '3 片'], ['生抽', '1 汤匙'], ['老抽', '半小勺'], ['盐', '少量']], steps: ['鸭腿洗净划几刀。', '锅中少油把鸭腿两面煎香。', '放姜片、生抽、老抽和热水。', '小火焖 35 分钟。', '收汁后切块装盘。'] }),
  recipe({ id: 'ham-steamed-egg', name: '火腿蒸蛋', subtitle: '嫩滑咸香，早餐晚餐都能吃', category: '蒸菜', time: 18, difficulty: 1, calories: 240, protein: 18, tags: ['新手友好', '清淡'], mainIngredientIds: ['ham', 'egg'], ingredientIds: ['ham', 'egg', 'scallion'], ingredients: [['火腿', '几片'], ['鸡蛋', '2 个'], ['温水', '蛋液 1.5 倍'], ['盐', '少量'], ['小葱', '少量']], steps: ['鸡蛋打散，加入温水和盐。', '撇去表面泡沫。', '火腿切丁放入蛋液。', '盖上盘子中小火蒸 10 分钟。', '撒小葱即可。'] }),
  recipe({ id: 'duck-egg-greens-soup', name: '鸭蛋青菜汤', subtitle: '味道比鸡蛋更香，汤也轻', category: '汤菜', time: 12, difficulty: 1, calories: 190, protein: 13, fatLoss: true, tags: ['热汤', '快手'], mainIngredientIds: ['duck_egg', 'bok_choy'], ingredientIds: ['duck_egg', 'bok_choy', 'scallion'], ingredients: [['鸭蛋', '1 个'], ['小青菜', '1 把'], ['小葱', '少量'], ['盐', '适量']], steps: ['鸭蛋打散，小青菜洗净。', '锅中加水烧开。', '放青菜煮软。', '淋入鸭蛋液成蛋花。', '加盐和小葱即可。'] }),
  recipe({ id: 'century-egg-tofu', name: '皮蛋豆腐', subtitle: '不开火，三分钟端上桌', category: '凉拌菜', time: 6, difficulty: 1, calories: 220, protein: 16, fatLoss: true, tags: ['清爽', '豆制品'], mainIngredientIds: ['century_egg', 'soft_tofu'], ingredientIds: ['century_egg', 'soft_tofu', 'scallion'], ingredients: [['皮蛋', '1 个'], ['嫩豆腐', '1 盒'], ['生抽', '1 小勺'], ['香醋', '1 小勺'], ['小葱', '少量']], steps: ['嫩豆腐倒入盘中。', '皮蛋去壳切块。', '把皮蛋放在豆腐上。', '淋生抽和香醋。', '撒小葱即可。'] }),
  recipe({ id: 'salted-egg-tofu', name: '咸蛋黄豆腐', subtitle: '咸香绵密，拌饭也很合适', category: '家常菜', time: 18, difficulty: 2, calories: 330, protein: 18, tags: ['豆制品', '下饭'], mainIngredientIds: ['salted_duck_egg', 'firm_tofu'], ingredientIds: ['salted_duck_egg', 'firm_tofu', 'scallion'], ingredients: [['咸鸭蛋', '1 个'], ['老豆腐', '1 块'], ['小葱', '少量'], ['盐', '少量']], steps: ['老豆腐切小块。', '咸鸭蛋压碎，取蛋黄和少量蛋白。', '锅中少油炒咸蛋黄到起泡。', '放豆腐和少量水煮 3 分钟。', '撒小葱出锅。'] }),
  recipe({ id: 'quail-egg-braised-pork', name: '鹌鹑蛋红烧肉', subtitle: '小蛋吸满肉汁，很适合周末', category: '炖菜', time: 45, difficulty: 2, calories: 620, protein: 34, tags: ['红烧', '下饭'], mainIngredientIds: ['quail_egg', 'pork_belly'], ingredientIds: ['quail_egg', 'pork_belly', 'ginger'], ingredients: [['鹌鹑蛋', '10 个'], ['五花肉', '250 克'], ['姜片', '3 片'], ['生抽', '1 汤匙'], ['老抽', '半小勺']], steps: ['鹌鹑蛋煮熟剥壳。', '五花肉切块焯水。', '锅中炒五花肉到出油。', '加调料和热水炖 30 分钟。', '放鹌鹑蛋再煮 10 分钟收汁。'] }),
  recipe({ id: 'tofu-skin-pork', name: '千张炒肉丝', subtitle: '豆香和肉香都在，带饭很好', category: '家常肉菜', time: 18, difficulty: 2, calories: 380, protein: 32, tags: ['豆制品', '下饭'], mainIngredientIds: ['tofu_skin', 'pork_loin'], ingredientIds: ['tofu_skin', 'pork_loin', 'green_pepper'], ingredients: [['千张', '2 张'], ['里脊肉', '150 克'], ['青椒', '1 个'], ['生抽', '1 汤匙'], ['盐', '少量']], steps: ['千张切丝，肉切丝，青椒切丝。', '肉丝加生抽抓匀。', '锅中少油炒肉丝。', '放千张和青椒翻炒。', '加盐调味出锅。'] }),
  recipe({ id: 'tofu-dry-celery', name: '豆腐干炒芹菜', subtitle: '清香耐嚼，十几分钟搞定', category: '家常素菜', time: 14, difficulty: 1, calories: 220, protein: 18, fatLoss: true, tags: ['豆制品', '清爽'], mainIngredientIds: ['tofu_dry', 'celery'], ingredientIds: ['tofu_dry', 'celery'], ingredients: [['豆腐干', '3 块'], ['芹菜', '1 把'], ['生抽', '1 小勺'], ['盐', '少量']], steps: ['豆腐干切条，芹菜切段。', '锅中少油，放豆腐干翻炒。', '放芹菜继续翻炒。', '加入生抽和盐。', '芹菜断生后出锅。'] }),
  recipe({ id: 'yuba-fungus-pork', name: '腐竹木耳炒肉', subtitle: '口感丰富，一盘很能下饭', category: '家常肉菜', time: 22, difficulty: 2, calories: 420, protein: 30, tags: ['豆制品', '下饭'], mainIngredientIds: ['yuba', 'black_fungus', 'pork'], ingredientIds: ['yuba', 'black_fungus', 'pork', 'garlic'], ingredients: [['腐竹', '1 把'], ['木耳', '1 小把'], ['猪肉末', '80 克'], ['大蒜', '2 瓣'], ['生抽', '1 汤匙']], steps: ['腐竹和木耳提前泡发。', '锅中少油炒散肉末。', '放蒜末炒香。', '放腐竹和木耳翻炒。', '加生抽和少量水焖 2 分钟。'] }),
  recipe({ id: 'fried-tofu-cabbage-pot', name: '油豆腐白菜煲', subtitle: '热乎有汤，素菜也吃得饱', category: '汤煲', time: 20, difficulty: 1, calories: 260, protein: 15, fatLoss: true, tags: ['热汤', '豆制品'], mainIngredientIds: ['fried_tofu', 'cabbage'], ingredientIds: ['fried_tofu', 'cabbage', 'garlic'], ingredients: [['油豆腐', '8 个'], ['白菜', '半颗'], ['大蒜', '2 瓣'], ['盐', '适量'], ['清水', '1 碗']], steps: ['白菜切块，油豆腐对半切开。', '锅中少油炒香蒜末。', '放白菜翻炒到变软。', '加水和油豆腐煮 8 分钟。', '加盐调味出锅。'] }),
  recipe({ id: 'soybean-sprout-vermicelli', name: '黄豆芽炒粉丝', subtitle: '便宜大份，适合想吃点主食感', category: '家常素菜', time: 16, difficulty: 1, calories: 300, protein: 14, tags: ['素菜', '主食感'], mainIngredientIds: ['soybean_sprouts', 'vermicelli'], ingredientIds: ['soybean_sprouts', 'vermicelli', 'garlic'], ingredients: [['黄豆芽', '1 把'], ['粉丝', '1 小把'], ['大蒜', '2 瓣'], ['生抽', '1 汤匙'], ['盐', '少量']], steps: ['粉丝泡软，黄豆芽洗净。', '锅中少油炒香蒜末。', '放黄豆芽炒到断生。', '放粉丝和生抽翻炒。', '加盐调味出锅。'] }),
  recipe({ id: 'mungbean-sprout-chive', name: '绿豆芽炒韭菜', subtitle: '清脆香，晚餐补菜很快', category: '素菜', time: 10, difficulty: 1, calories: 150, protein: 8, fatLoss: true, tags: ['清爽', '快手'], mainIngredientIds: ['mungbean_sprouts', 'chive'], ingredientIds: ['mungbean_sprouts', 'chive'], ingredients: [['绿豆芽', '1 把'], ['韭菜', '半把'], ['盐', '少量'], ['食用油', '少量']], steps: ['绿豆芽洗净，韭菜切段。', '锅中少油烧热。', '先放绿豆芽快速翻炒。', '放韭菜继续炒 30 秒。', '加盐后马上出锅。'] }),
  recipe({ id: 'steamed-fish', name: '清蒸鱼', subtitle: '鱼肉鲜嫩，少油也好吃', category: '蒸菜', time: 25, difficulty: 2, calories: 320, protein: 36, fatLoss: true, tags: ['清淡', '高蛋白'], mainIngredientIds: ['whole_fish'], ingredientIds: ['whole_fish', 'ginger', 'scallion'], ingredients: [['鱼', '1 条'], ['姜丝', '适量'], ['小葱', '适量'], ['蒸鱼豉油', '1 汤匙']], steps: ['鱼处理干净，两面划几刀。', '铺姜丝，上锅蒸 10 到 12 分钟。', '倒掉盘中腥水。', '淋蒸鱼豉油，撒葱丝。', '少量热油淋在葱丝上即可。'] }),
  recipe({ id: 'boiled-prawn', name: '白灼基围虾', subtitle: '鲜甜低负担，做法很简单', category: '海鲜', time: 12, difficulty: 1, calories: 210, protein: 30, fatLoss: true, tags: ['清爽', '高蛋白'], mainIngredientIds: ['prawn'], ingredientIds: ['prawn', 'ginger'], ingredients: [['基围虾', '250 克'], ['姜片', '3 片'], ['盐', '少量'], ['清水', '适量']], steps: ['基围虾洗净。', '锅中加水、姜片和少量盐煮开。', '放入虾煮到变红弯曲。', '捞出沥干。', '可蘸少量生抽食用。'] }),
  recipe({ id: 'garlic-scallop-vermicelli', name: '蒜蓉粉丝扇贝', subtitle: '看起来精致，其实步骤不复杂', category: '蒸菜', time: 22, difficulty: 2, calories: 280, protein: 26, tags: ['海鲜', '蒜香'], mainIngredientIds: ['scallop', 'vermicelli'], ingredientIds: ['scallop', 'vermicelli', 'garlic'], ingredients: [['扇贝', '6 个'], ['粉丝', '1 小把'], ['大蒜', '4 瓣'], ['生抽', '1 汤匙']], steps: ['粉丝泡软，扇贝洗净。', '大蒜切末，少油炒香。', '粉丝铺在扇贝上。', '放蒜蓉和生抽，上锅蒸 8 分钟。', '蒸熟后即可上桌。'] }),
  recipe({ id: 'clam-vermicelli-pot', name: '花甲粉丝煲', subtitle: '鲜味足，一锅就很像夜宵摊', category: '汤煲', time: 22, difficulty: 2, calories: 320, protein: 28, tags: ['海鲜', '热汤'], mainIngredientIds: ['clam', 'vermicelli'], ingredientIds: ['clam', 'vermicelli', 'garlic'], ingredients: [['花甲', '300 克'], ['粉丝', '1 小把'], ['大蒜', '3 瓣'], ['生抽', '1 汤匙'], ['清水', '1 碗']], steps: ['花甲吐沙洗净，粉丝泡软。', '锅中少油炒香蒜末。', '放花甲和清水煮开。', '花甲开口后放粉丝。', '加生抽调味，煮 2 分钟出锅。'] }),
  recipe({ id: 'seaweed-egg-soup', name: '紫菜蛋花汤', subtitle: '最快的热汤，配主食刚好', category: '汤菜', time: 8, difficulty: 1, calories: 120, protein: 9, fatLoss: true, tags: ['快手汤', '清淡'], mainIngredientIds: ['seaweed', 'egg'], ingredientIds: ['seaweed', 'egg', 'scallion'], ingredients: [['紫菜', '一小片'], ['鸡蛋', '1 个'], ['小葱', '少量'], ['盐', '适量']], steps: ['鸡蛋打散，小葱切碎。', '锅中加水烧开。', '放入紫菜。', '淋入蛋液形成蛋花。', '加盐和小葱即可。'] }),
  recipe({ id: 'kelp-ribs-soup', name: '海带排骨汤', subtitle: '鲜香清爽，适合想喝汤的时候', category: '汤菜', time: 45, difficulty: 2, calories: 390, protein: 30, tags: ['热汤', '炖菜'], mainIngredientIds: ['kelp', 'ribs'], ingredientIds: ['kelp', 'ribs', 'ginger'], ingredients: [['海带', '1 把'], ['排骨', '250 克'], ['姜片', '3 片'], ['盐', '适量']], steps: ['排骨焯水洗净。', '海带泡好切片。', '锅中加排骨、姜片和热水。', '炖 30 分钟后放海带。', '再煮 10 分钟，加盐调味。'] }),
  recipe({ id: 'squid-green-pepper', name: '鱿鱼炒青椒', subtitle: '鲜香有锅气，米饭很搭', category: '家常海鲜', time: 18, difficulty: 2, calories: 260, protein: 28, tags: ['椒香锅气', '下饭'], mainIngredientIds: ['squid', 'green_pepper'], ingredientIds: ['squid', 'green_pepper', 'garlic'], ingredients: [['鱿鱼', '200 克'], ['青椒', '2 个'], ['大蒜', '2 瓣'], ['生抽', '1 汤匙'], ['盐', '少量']], steps: ['鱿鱼切花刀或切片，青椒切块。', '鱿鱼焯水 20 秒捞出。', '锅中少油炒香蒜片。', '放青椒和鱿鱼大火翻炒。', '加生抽和盐调味出锅。'] }),
  recipe({ id: 'oyster-steamed-egg', name: '生蚝蒸蛋', subtitle: '嫩滑鲜美，适合想吃高蛋白', category: '蒸菜', time: 18, difficulty: 2, calories: 260, protein: 24, fatLoss: true, tags: ['高蛋白', '清淡'], mainIngredientIds: ['oyster', 'egg'], ingredientIds: ['oyster', 'egg', 'scallion'], ingredients: [['生蚝肉', '100 克'], ['鸡蛋', '2 个'], ['温水', '蛋液 1.5 倍'], ['小葱', '少量']], steps: ['鸡蛋打散，加温水搅匀。', '撇去泡沫后倒入碗中。', '盖盘蒸 8 分钟。', '放生蚝肉再蒸 4 分钟。', '撒小葱，淋少量生抽。'] }),
  recipe({ id: 'crayfish-rice-cake', name: '小龙虾炒年糕', subtitle: '重口一点，适合周末解馋', category: '家常海鲜', time: 25, difficulty: 2, calories: 520, protein: 28, tags: ['香辣', '主食'], mainIngredientIds: ['crayfish', 'rice_cake'], ingredientIds: ['crayfish', 'rice_cake', 'dried_chili', 'garlic'], ingredients: [['小龙虾尾', '250 克'], ['年糕', '150 克'], ['大蒜', '3 瓣'], ['干辣椒', '少量'], ['生抽', '1 汤匙']], steps: ['年糕焯水变软。', '锅中少油炒香蒜和干辣椒。', '放小龙虾尾翻炒。', '加入年糕和生抽。', '加少量水焖 3 分钟收汁。'] }),
  recipe({ id: 'steamed-crab', name: '清蒸大闸蟹', subtitle: '食材好时，简单蒸就够鲜', category: '蒸菜', time: 22, difficulty: 2, calories: 260, protein: 30, tags: ['海鲜', '清蒸'], mainIngredientIds: ['crab'], ingredientIds: ['crab', 'ginger'], ingredients: [['大闸蟹', '2 只'], ['姜片', '几片'], ['香醋', '少量']], steps: ['大闸蟹刷洗干净。', '蒸锅铺姜片。', '蟹肚朝上放入蒸锅。', '水开后蒸 15 分钟。', '搭配姜醋汁食用。'] }),
  recipe({ id: 'flour-egg-pancake', name: '面粉鸡蛋饼', subtitle: '冰箱没菜也能做的主食', category: '主食', time: 12, difficulty: 1, calories: 360, protein: 16, tags: ['主食', '快手'], mainIngredientIds: ['flour', 'egg'], ingredientIds: ['flour', 'egg', 'scallion'], ingredients: [['面粉', '半碗'], ['鸡蛋', '1 个'], ['小葱', '少量'], ['盐', '少量'], ['清水', '适量']], steps: ['面粉加鸡蛋、盐和清水搅成面糊。', '加入小葱搅匀。', '平底锅刷少量油。', '倒入面糊摊平。', '两面煎到金黄即可。'] }),
  recipe({ id: 'egg-mantou-slices', name: '鸡蛋煎馒头片', subtitle: '剩馒头变香，早餐晚餐都能顶上', category: '主食', time: 10, difficulty: 1, calories: 360, protein: 14, tags: ['主食', '快手'], mainIngredientIds: ['mantou', 'egg'], ingredientIds: ['mantou', 'egg'], ingredients: [['馒头', '1 个'], ['鸡蛋', '1 个'], ['盐', '少量'], ['食用油', '少量']], steps: ['馒头切片，鸡蛋加盐打散。', '馒头片裹上蛋液。', '平底锅少油烧热。', '放入馒头片小火煎。', '两面金黄后出锅。'] }),
  recipe({ id: 'baozi-egg-pan', name: '抱蛋煎包', subtitle: '包子加蛋，直接变一餐', category: '主食', time: 14, difficulty: 1, calories: 460, protein: 18, tags: ['主食', '快手'], mainIngredientIds: ['baozi', 'egg'], ingredientIds: ['baozi', 'egg', 'scallion'], ingredients: [['包子', '3 个'], ['鸡蛋', '1 个'], ['小葱', '少量'], ['食用油', '少量']], steps: ['鸡蛋打散，小葱切碎。', '平底锅少油，放包子煎底部。', '沿锅边加少量水焖 3 分钟。', '倒入蛋液煎定型。', '撒小葱后出锅。'] }),
  recipe({ id: 'dumpling-egg-pan', name: '饺子煎蛋', subtitle: '速冻饺子也能做得像正餐', category: '主食', time: 16, difficulty: 1, calories: 520, protein: 22, tags: ['主食', '快手'], mainIngredientIds: ['dumpling', 'egg'], ingredientIds: ['dumpling', 'egg', 'scallion'], ingredients: [['饺子', '8 个'], ['鸡蛋', '1 个'], ['小葱', '少量'], ['食用油', '少量']], steps: ['饺子放平底锅煎到底部微黄。', '加少量水盖盖焖熟。', '水快干时倒入蛋液。', '小火煎到蛋液凝固。', '撒小葱出锅。'] }),
  recipe({ id: 'rice-noodle-egg', name: '米粉炒鸡蛋', subtitle: '比炒饭更轻快的一人食', category: '主食', time: 16, difficulty: 2, calories: 480, protein: 18, tags: ['主食', '一人食'], mainIngredientIds: ['rice_noodle', 'egg'], ingredientIds: ['rice_noodle', 'egg', 'bok_choy'], ingredients: [['米粉', '1 人份'], ['鸡蛋', '1 个'], ['小青菜', '1 把'], ['生抽', '1 小勺'], ['盐', '少量']], steps: ['米粉泡软，鸡蛋打散，小青菜洗净。', '锅中少油炒鸡蛋。', '放米粉翻炒。', '加入小青菜和生抽。', '炒匀调味出锅。'] }),
  recipe({ id: 'rice-cake-cabbage', name: '年糕炒白菜', subtitle: '软糯又有菜，晚餐很省事', category: '主食', time: 18, difficulty: 2, calories: 420, protein: 10, tags: ['主食', '素菜'], mainIngredientIds: ['rice_cake', 'cabbage'], ingredientIds: ['rice_cake', 'cabbage', 'garlic'], ingredients: [['年糕', '150 克'], ['白菜', '半颗'], ['大蒜', '2 瓣'], ['生抽', '1 小勺'], ['盐', '少量']], steps: ['年糕焯水变软，白菜切段。', '锅中少油炒香蒜末。', '放白菜炒软。', '加入年糕和生抽翻炒。', '加盐调味出锅。'] }),
  recipe({ id: 'apple-banana-yogurt', name: '苹果香蕉酸奶碗', subtitle: '不想开火时的轻食选择', category: '水果轻食', time: 6, difficulty: 1, calories: 260, protein: 8, fatLoss: true, tags: ['清爽', '水果'], mainIngredientIds: ['apple', 'banana'], ingredientIds: ['apple', 'banana'], ingredients: [['苹果', '半个'], ['香蕉', '1 根'], ['无糖酸奶', '适量']], steps: ['苹果洗净切块。', '香蕉切片。', '把水果放入碗中。', '加入无糖酸奶。', '轻轻拌匀即可。'] }),
  recipe({ id: 'pear-citrus-bowl', name: '梨橘柚子水果碗', subtitle: '清甜多汁，适合饭后轻一点', category: '水果轻食', time: 8, difficulty: 1, calories: 220, protein: 2, fatLoss: true, tags: ['清爽', '水果'], mainIngredientIds: ['pear', 'mandarin', 'grapefruit'], ingredientIds: ['pear', 'mandarin', 'grapefruit'], ingredients: [['梨', '半个'], ['橘子', '1 个'], ['柚子', '几瓣']], steps: ['梨洗净切块。', '橘子剥瓣。', '柚子剥出果肉。', '三种水果放入碗中。', '冷藏几分钟口感更好。'] }),
  recipe({ id: 'strawberry-grape-yogurt', name: '草莓葡萄酸奶杯', subtitle: '酸甜清爽，适合下午或轻晚餐', category: '水果轻食', time: 6, difficulty: 1, calories: 240, protein: 7, fatLoss: true, tags: ['清爽', '水果'], mainIngredientIds: ['strawberry', 'grape'], ingredientIds: ['strawberry', 'grape'], ingredients: [['草莓', '6 个'], ['葡萄', '1 小把'], ['无糖酸奶', '适量']], steps: ['草莓和葡萄洗净。', '草莓去蒂对半切。', '葡萄可对半切开。', '倒入酸奶。', '轻轻拌匀即可。'] }),
  recipe({ id: 'watermelon-tomato-salad', name: '西瓜番茄沙拉', subtitle: '清爽酸甜，夏天很适合', category: '水果轻食', time: 8, difficulty: 1, calories: 180, protein: 4, fatLoss: true, tags: ['清爽', '酸甜开胃'], mainIngredientIds: ['watermelon', 'tomato'], ingredientIds: ['watermelon', 'tomato'], ingredients: [['西瓜', '几块'], ['番茄', '1 个'], ['盐', '少量']], steps: ['西瓜去籽切块。', '番茄洗净切块。', '水果放入碗中。', '撒一点点盐提味。', '拌匀后食用。'] }),
  recipe({ id: 'mango-chicken-salad', name: '芒果鸡胸沙拉', subtitle: '甜香配高蛋白，减脂也不单调', category: '轻食', time: 18, difficulty: 2, calories: 360, protein: 34, fatLoss: true, tags: ['高蛋白', '水果'], mainIngredientIds: ['mango', 'chicken_breast'], ingredientIds: ['mango', 'chicken_breast', 'lettuce'], ingredients: [['芒果', '半个'], ['鸡胸肉', '180 克'], ['生菜', '几片'], ['盐和黑胡椒', '少量']], steps: ['鸡胸肉用盐和黑胡椒腌一下。', '煎熟后切片。', '芒果切块，生菜洗净。', '把食材放入盘中。', '按口味加少量油醋汁。'] }),
  recipe({ id: 'dragon-kiwi-cup', name: '火龙果猕猴桃杯', subtitle: '颜色好看，饭后想清爽就吃它', category: '水果轻食', time: 6, difficulty: 1, calories: 210, protein: 4, fatLoss: true, tags: ['清爽', '水果'], mainIngredientIds: ['dragon_fruit', 'kiwi'], ingredientIds: ['dragon_fruit', 'kiwi'], ingredients: [['火龙果', '半个'], ['猕猴桃', '1 个'], ['无糖酸奶', '可选']], steps: ['火龙果去皮切块。', '猕猴桃去皮切片。', '放入杯中或碗中。', '可加入少量无糖酸奶。', '冷藏后更清爽。'] }),
  recipe({ id: 'peach-cherry-yogurt', name: '桃子樱桃酸奶碗', subtitle: '甜香轻盈，不用开火', category: '水果轻食', time: 6, difficulty: 1, calories: 230, protein: 7, fatLoss: true, tags: ['清爽', '水果'], mainIngredientIds: ['peach', 'cherry'], ingredientIds: ['peach', 'cherry'], ingredients: [['桃子', '1 个'], ['樱桃', '几颗'], ['无糖酸奶', '适量']], steps: ['桃子洗净切块。', '樱桃洗净去核。', '水果放入碗中。', '加入无糖酸奶。', '拌匀即可。'] }),
  recipe({ id: 'orange-shrimp-salad', name: '橙子虾仁沙拉', subtitle: '清甜鲜爽，晚餐吃起来轻', category: '轻食', time: 15, difficulty: 2, calories: 280, protein: 26, fatLoss: true, tags: ['清爽', '高蛋白'], mainIngredientIds: ['orange', 'shrimp'], ingredientIds: ['orange', 'shrimp', 'lettuce'], ingredients: [['橙子', '1 个'], ['虾仁', '150 克'], ['生菜', '几片'], ['盐', '少量']], steps: ['虾仁焯熟沥干。', '橙子剥出果肉。', '生菜洗净撕小片。', '食材放入盘中。', '按口味加少量盐或油醋汁。'] }),
  recipe({ id: 'mushroom-chicken-leg-pot', name: '香菇鸡腿煲', subtitle: '鸡腿肉多一个靠谱选择', category: '家常肉菜', time: 30, difficulty: 2, calories: 480, protein: 36, tags: ['一锅菜', '下饭'], mainIngredientIds: ['chicken_thigh', 'mushroom'], ingredientIds: ['chicken_thigh', 'mushroom', 'ginger'], ingredients: [['鸡腿肉', '250 克'], ['香菇', '6 朵'], ['姜片', '3 片'], ['生抽', '1 汤匙'], ['盐', '少量']], steps: ['鸡腿肉切块，香菇切片。', '锅中少油炒香姜片和鸡腿肉。', '放香菇翻炒。', '加生抽和少量水焖 15 分钟。', '加盐收汁出锅。'] }),
  recipe({ id: 'green-pepper-pork', name: '辣椒炒肉', subtitle: '青椒香、肉片嫩，很适合配米饭', category: '家常肉菜', time: 18, difficulty: 2, calories: 430, protein: 26, tags: ['椒香锅气', '下饭', '家常'], mainIngredientIds: ['green_pepper', 'pork_belly'], ingredientIds: ['green_pepper', 'pork_belly', 'dried_chili', 'garlic'], ingredients: [['五花肉', '220 克'], ['青椒', '3 个'], ['大蒜', '3 瓣'], ['干辣椒', '2 个，可不放'], ['生抽', '1 汤匙'], ['老抽', '半小勺'], ['盐', '少量']], steps: ['五花肉切薄片，青椒去籽切斜段，大蒜切片。', '锅烧热后放五花肉，小火煸到边缘微卷出油。', '放蒜片和干辣椒炒香。', '放青椒大火翻炒到微微变软。', '加入生抽、老抽和少量盐，炒匀后出锅。'] }),
  recipe({ id: 'braised-chicken-thigh', name: '卤鸡腿', subtitle: '酱香入味，晚餐带饭都很稳', category: '家常肉菜', time: 40, difficulty: 2, calories: 520, protein: 42, tags: ['酱香', '下饭', '鸡腿'], mainIngredientIds: ['chicken_thigh'], ingredientIds: ['chicken_thigh', 'ginger', 'scallion'], ingredients: [['鸡腿', '2 只'], ['姜片', '3 片'], ['小葱', '2 根'], ['生抽', '1 汤匙'], ['老抽', '半小勺'], ['冰糖', '少量'], ['清水', '1 碗']], steps: ['鸡腿洗净，两面各划两刀，姜切片，小葱打结。', '锅中少油，把鸡腿两面煎到表皮微黄。', '加入姜片、小葱、生抽、老抽、冰糖和清水。', '水开后转小火焖 25 到 30 分钟，中途翻面一次。', '开盖收汁，汤汁浓稠后夹出鸡腿即可。'] }),
  recipe({ id: 'scallion-chicken-thigh-rice', name: '葱油鸡腿饭', subtitle: '鸡腿嫩、葱油香，一碗就够满足', category: '主食', time: 25, difficulty: 2, calories: 610, protein: 40, tags: ['主食', '鸡腿', '下饭'], mainIngredientIds: ['chicken_thigh', 'rice'], ingredientIds: ['chicken_thigh', 'rice', 'scallion', 'cucumber'], ingredients: [['鸡腿肉', '220 克'], ['米饭', '1 碗'], ['小葱', '2 根'], ['黄瓜', '半根'], ['生抽', '1 汤匙'], ['食用油', '少量'], ['盐', '少量']], steps: ['鸡腿肉用少量盐和生抽抓匀，黄瓜切条，小葱切末。', '平底锅少油，鸡腿肉皮面朝下煎到金黄。', '翻面继续煎熟，切成厚片。', '米饭盛入碗中，铺上黄瓜和鸡腿肉。', '锅里留少量热油炒香葱末，淋在鸡腿饭上即可。'] }),
  recipe({ id: 'teriyaki-chicken-thigh-rice', name: '照烧鸡腿饭', subtitle: '甜咸酱汁挂满鸡腿，新手也能做', category: '主食', time: 28, difficulty: 2, calories: 650, protein: 42, tags: ['主食', '酱香', '鸡腿'], mainIngredientIds: ['chicken_thigh', 'rice'], ingredientIds: ['chicken_thigh', 'rice', 'bok_choy'], ingredients: [['鸡腿肉', '240 克'], ['米饭', '1 碗'], ['小青菜', '1 把'], ['生抽', '1 汤匙'], ['老抽', '半小勺'], ['糖', '半小勺'], ['清水', '半碗']], steps: ['鸡腿肉去骨或拍平，小青菜洗净。', '锅中少油，把鸡腿肉两面煎到金黄。', '加入生抽、老抽、糖和清水。', '小火煮到鸡腿熟透，酱汁变浓。', '米饭装碗，放上鸡腿和焯熟的小青菜，淋上酱汁。'] }),
  recipe({ id: 'garlic-chicken-wing', name: '蒜香鸡翅', subtitle: '不用复杂调料，也能很香', category: '家常肉菜', time: 26, difficulty: 2, calories: 460, protein: 32, tags: ['蒜香', '下饭'], mainIngredientIds: ['chicken_wing', 'garlic'], ingredientIds: ['chicken_wing', 'garlic'], ingredients: [['鸡翅', '6 个'], ['大蒜', '4 瓣'], ['生抽', '1 汤匙'], ['盐', '少量']], steps: ['鸡翅两面划刀，大蒜切末。', '鸡翅加生抽和蒜末腌 10 分钟。', '平底锅少油煎鸡翅。', '两面金黄后加少量水焖熟。', '收汁后出锅。'] }),
  recipe({ id: 'garlic-fish-fillet', name: '蒜香鱼片', subtitle: '鱼片不只做汤，快炒也很香', category: '家常海鲜', time: 16, difficulty: 2, calories: 260, protein: 30, fatLoss: true, tags: ['高蛋白', '蒜香'], mainIngredientIds: ['fish_fillet', 'garlic'], ingredientIds: ['fish_fillet', 'garlic', 'scallion'], ingredients: [['鱼片', '200 克'], ['大蒜', '3 瓣'], ['小葱', '少量'], ['盐', '少量'], ['淀粉', '1 小勺']], steps: ['鱼片加盐和淀粉轻轻抓匀。', '锅中少油炒香蒜末。', '放鱼片轻轻滑炒。', '鱼片变白熟透后调味。', '撒小葱出锅。'] }),
  recipe({ id: 'shrimp-corn-egg', name: '虾仁玉米滑蛋', subtitle: '鲜甜嫩滑，小朋友也容易接受', category: '家常快手', time: 15, difficulty: 1, calories: 330, protein: 28, tags: ['快手', '高蛋白'], mainIngredientIds: ['shrimp', 'corn', 'egg'], ingredientIds: ['shrimp', 'corn', 'egg'], ingredients: [['虾仁', '120 克'], ['玉米粒', '半碗'], ['鸡蛋', '2 个'], ['盐', '少量']], steps: ['虾仁洗净，玉米粒备好，鸡蛋打散。', '锅中少油炒虾仁到变色。', '放玉米粒翻炒。', '倒入蛋液小火推炒。', '蛋液刚凝固时加盐出锅。'] })
];

module.exports = {
  ingredientCategories,
  categoryOverrides,
  extraIngredients,
  extraRecipes
};
